# yazi.toml

[manager]
ratio = [1, 4, 3]
show_hidden = true
show_symlink_path = true

# [opener]
# edit = [
#   { run = 'nu ~/.config/yazelix/nushell/open_file.nu "$1"', desc = "Open File in a new pane" },
# ]

[[plugin.prepend_fetchers]]
id = "git"
name = "*"
run = "git"

[[plugin.prepend_fetchers]]
id = "git"
name = "*/"
run = "git"
