# yazi.toml

[manager]
ratio = [1, 4, 3]
show_hidden = true
show_symlink_path = true

[opener]
play = [
	{ run = 'mpv "$@"', orphan = true, for = "unix" },
]
edit = [
	{ run = '$EDITOR "$@"', block = true, for = "unix" },
]
open = [
	{ run = 'xdg-open "$@"', desc = "Open" },
]

[[plugin.prepend_fetchers]]
id = "git"
name = "*"
run = "git"
