# yazi.toml

[manager]
ratio = [1, 4, 3]
show_hidden = true
show_symlink_path = true

# [opener]
# edit = [
#   { run = 'bash ~/.config/yazi/open_file.sh "$1"' }
# ]

[[plugin.prepend_fetchers]]
id = "git"
name = "*"
run = "git"
